### PR TITLE
#50 Update html-minifier to v1.5.0 (at least)

### PR DESCRIPTION
**Pull request by dackmin**

### CODE REVIEW

**Comment by dackmin** [comment]
up 😄

**Comment by JohnPostlethwait** [comment]
Sorry, was on vacation, looking at it now.

**Comment by nikku** [comment]
Could you cut a release with the changes?

**Comment by JohnPostlethwait** [comment]
Oops, yes! Sorry about that, will do so now and let you know.

**Comment by JohnPostlethwait** [comment]
Version 5.2.0 up on NPM - sorry for the delay!

https://www.npmjs.com/package/stringify

**Pull request merged**
